# dependabot.yml
#
# Copyright (c) 2021 Kano Computing Ltd.
#
# Automatated dependency upgrades for the project.


version: 2
updates:
- package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: "daily"
    time: "01:00"
    timezone: "Europe/London"
