# azure-pipelines-ci.yml
#
# Copyright (c) 2020 Kano Computing Ltd.
#
# Continuous integration pipeline for the project.


trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

variables:
  major: 1
  minor: 5
  patch: $[counter(variables['major'].variables['minor'].*, 0)]

# Customise the Build.BuildNumber variable with the version of the build.
name: '$(major).$(minor).$(patch)'

resources:
  repositories:
  - repository: templates
    type: github
    name: KanoComputing/azure-pipeline-templates
    endpoint: KanoComputing
    ref: refs/tags/1.0.4

stages:
- stage: Test
  jobs:
  - job: Test
    steps:
    - template: steps/run-visual-studio-tests.yml@templates

- stage: Build
  # Remove implicit dependency on previous stage and run in parallel.
  dependsOn: []
  jobs:
  - job: Build
    steps:
    - template: steps/build-nuget-package.yml@templates
      parameters:
        projectName: 'KpcUwpCore'
