# azure-pipelines-cd.yml
#
# Copyright (c) 2021 Kano Computing Ltd.
#
# Continuous deployment pipeline for the project.


trigger: none
pr: none

resources:
  pipelines:
  - pipeline: ci
    source: 'KpcUwpCore CI'
    branch: master
    trigger:
      branches:
        include:
        - master
  repositories:
  - repository: templates
    type: github
    name: KanoComputing/azure-pipeline-templates
    endpoint: KanoComputing
    ref: refs/tags/4.1.3


stages:
- template: stages/release-initialisation.yml@templates
  parameters:
    buildNumber: '$(resources.pipeline.ci.runName)'

- stage: ProductionPreview
  displayName: 'Release to ProductionPreview'
  jobs:
  - template: jobs/release-to-nuget.yml@templates
    parameters:
      environment: 'ProductionPreview'

- stage: Production
  displayName: 'Release to Production'
  jobs:
  - template: jobs/release-to-nuget.yml@templates
    parameters:
      environment: 'Production'

  - deployment: UploadLibs
    displayName: 'Upload libraries to Kano PC bucket'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: steps/kano-pc-bucket-upload.yml@templates
            parameters:
              globExpressions: |
                **/*.nupkg
                !**/*WinRT*
                !**/*.symbols.nupkg
              targetFolder: 'libs/prod/kpc-uwp-core'

          - template: steps/kano-pc-bucket-upload.yml@templates
            parameters:
              globExpressions: |
                **/*WinRT*.nupkg
                !**/*.symbols.nupkg
              targetFolder: 'libs/prod/kpc-uwp-core-winrt'

- template: stages/release-documentation.yml@templates
