# azure-pipelines-ci.yml
#
# Copyright (c) 2020 Kano Computing Ltd.
#
# Continuous integration pipeline for the project.


trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - '*'

variables:
  major: 3
  minor: 2
  patch: $[counter(format('{0}.{1}', variables['major'], variables['minor']), 0)]

# Customise the Build.BuildNumber variable with the version of the build.
name: '$(major).$(minor).$(patch)'

resources:
  repositories:
  - repository: templates
    type: github
    name: KanoComputing/azure-pipeline-templates
    endpoint: KanoComputing
    ref: refs/tags/4.0.0

pool:
  vmImage: 'windows-latest'


stages:
- stage: Test
  jobs:
  - job: Test
    steps:
    - template: steps/run-visual-studio-tests.yml@templates

- stage: Build
  dependsOn: []
  jobs:
  - job: Build
    steps:
    - template: steps/build-nuget-package.yml@templates
      parameters:
        projectName: 'KpcUwpCore'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish WinRT NuGet build artifacts'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\KpcUwpCoreWinRT\bin\Release\Package'
        ArtifactName: 'KpcUwpCoreWinRT'
        publishLocation: 'Container'
