# azure-pipelines-cd.yml
#
# Copyright (c) 2020 Kano Computing Ltd.
#
# Continuous deployment pipeline for the project.


trigger: none
pr: none

resources:
  # Trigger this pipeline whenever the corresponding CI pipeline finishes
  # successfully from the main branch.
  pipelines:
  - pipeline: ci
    source: 'KpcUwpCore CI'
    branch: master
    trigger:
      branches:
        include:
        - master

  repositories:
  - repository: templates
    type: github
    name: KanoComputing/azure-pipeline-templates
    endpoint: KanoComputing
    ref: refs/tags/2.0.6


stages:
- template: stages/release-initialisation.yml@templates
  parameters:
    buildNumber: '$(resources.pipeline.ci.runName)'

- stage: Staging
  displayName: 'Release to Staging'
  jobs:
  - template: jobs/release-to-nuget.yml@templates
    parameters:
      environment: 'Staging'

- stage: Production
  displayName: 'Release to Production'
  jobs:
  - template: jobs/release-to-nuget.yml@templates
    parameters:
      environment: 'Production'

- template: stages/release-documentation.yml@templates
